image: atlassian/default-image:4

definitions:
  steps:
    - step: &resource_allocation_report
        name: Resource Allocation Report
        script:
          - echo "CPUs = $(nproc)"
          - echo "RAM  = $(grep MemTotal /proc/meminfo | awk '{print $2 / 1024 / 1024 }') GB"
          - echo "Disk = $(df --block-size=1G / | awk 'NR==2 {print $2}') GB"

pipelines:
  default:
    - step:
        name: Default Size
        size: 1x
        <<: *resource_allocation_report
    - step: 
        name: Double Size
        size: 2x
        <<: *resource_allocation_report
