image: python:3.12

pipelines:
  default:
    - step:
        name: Run Data Analysis

        script:
          - pip install -r requirements.txt
          - python cluster_analysis.py

        artifacts:
          - analysis_report.md

