image: atlassian/default-image:4

pipelines:
  default:
    - step:
        name: Use a pipe from Docker Hub
        script:
          - pipe: docker://docker.io/hello-world:latest

    - step:
        name: Use a pipe from AWS Elastic Container Registry
        script:
          - pipe: docker://public.ecr.aws/docker/library/hello-world:linux

